# Generated by Django 5.2.6 on 2025-09-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
    ]
