# Generated by Django 5.1.5 on 2025-09-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_alter_teammember_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
