services:
  - type: web
    name: team-blog-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn blog_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: team-blog-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: team-blog-db
    plan: free
